#!/usr/bin/env bash
# TODO faudrait que je fasse de ce truc une archive.deb pour gerer les deps en auto, ou un salt,
# notamment pour l'install de python3 qu'on ne veut pas frocement et qui doit se barrer en --autoremove
# TODO mettre un vrai getopt
# TODO mettre une option uinstall
# TODO ne pas installer si lc repertoir cvim existe deja
# TODO mettre une option pour forcer linstall si cvim existe deja
# TODO il faut que le runtime ne pointe pas sur le repertoire .vim du user mais soit dans le reperter /usr/local/vim/.vim
# pareil pour le vim rc
# TODO faire un test en desinstallant le paquet python3, pour voir si juste le python3-dev suffit

set -e

function echo_y {
    echo -e '\e[1;33m'"$@"'\e[0m'
}

echo_y NE PAS OUBLIER DE VIRER LE COMM QUI EMPECHE LE GIT CLONE !!!

VIM_NAME=cvim # for "custom Vim"
INSTALL_PATH=/usr/local/${VIM_NAME}
DL_DIRPATH=/tmp/${VIM_NAME}


# Parse arguments.
usage() {
    echo 'Installs a custom version of the Vim editor at location '"${INSTALL_PATH}"'.'
    echo
    echo 'Usage : '"$(basename $0)"' [options]'
    echo 'Options :'
    echo '    -f : force install.'
}

OPTIND=1
FORCE_INSTALL=0
DO_DL=1
while getopts "hf" opt; do
    case "$opt" in
    h)
        usage
        exit 0
        ;;
    f)  FORCE_INSTALL=1
        ;;
    esac
done
shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if [ $# -gt 0 ]; then
    echo '[Error] Too may positional arguments.'
    echo
    usage
    exit 1
fi

#if [ $# -ne 1 ]; then
    #echo '[Error] Suffix is missing. Key name will be "id_rsa_${SUFFIX}".'
    #echo
    #usage
    #exit 1
#fi

# Check install directory.
if [ -e ${INSTALL_PATH} -a ${FORCE_INSTALL} -eq 0 ]; then
    echo "'""${INSTALL_PATH}""'"' already exists, use option -f to force install.'
    exit 1
fi

# First install dependencies needed for compilation.
# This may be incomplete as I created this script on a station which had
# already a lot of stuff installed. In such a case, compilation would fail with
# a message indicating the missing library (hopefully). This should be added to
# the list below.
echo_y 'Installing dependencies.'
sudo apt-get install -y \
    git\
    build-essential\
    cmake\
    python-dev\
    python3-dev\
    libncurses5-dev



echo_y 'Getting Vim sources from Github.'
#rm -rf ${DL_DIRPATH}
#git clone https://github.com/vim/vim.git ${DL_DIRPATH}

echo_y 'Configuring Vim.'
# cd ${DL_DIRPATH}
# ./configure \
#     --prefix=/usr/local/vim \
#     --enable-fail-if-missing \
#     --with-features=huge \
#     --disable-gui \
#     --with-x \
#     --enable-multibyte \
#     --enable-xim \
#     --enable-xsmp \
#     --disable-xsmp-interact \
#     --with-tlib=ncurses \
#     --enable-pythoninterp \
#     --enable-python3interp
# make clean
# make
# sudo make install
# rm -rf /tmp/vim
#git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
