#!/usr/bin/env bash
# TODO faire une petite boucle de grep pour parser les options de vim --version 
# pour check que j'ai tout ce que je veux : +clipboard, +python", etc
# clipboard, python, python3, cmdline_hist, vertsplit
# TODO ne pas installer si lc repertoir cvim existe deja
# TODO mettre une option pour forcer linstall si cvim existe deja
# TODO il faut que le runtime ne pointe pas sur le repertoire .vim du user mais soit dans le reperter /usr/local/vim/.vim
# pareil pour le vim rc

set -e

# 'echo' with yellow color.
function echo_y {
    echo -e '\e[1;33m'"$@"'\e[0m'
}

# 'echo' with green color.
function echo_g {
    echo -e '\e[1;36m'"$@"'\e[0m'
}

echo_y NE PAS OUBLIER DE REMOVE TOUS LES UNCOMMENT

VIM_NAME=customvim
INSTALL_PATH=/usr/local/${VIM_NAME}
DL_DIRPATH=/tmp/${VIM_NAME}


# Parse arguments.
usage() {
    echo "Installs a custom version of the Vim editor at location '${INSTALL_PATH}'."
    echo
    echo "Usage : '$(basename $0)' [options]"
    echo "Options :"
    echo "    -f : force install."
}

OPTIND=1
FORCE_INSTALL=0
while getopts "hf" opt; do
    case "$opt" in
    h)
        usage
        exit 0
        ;;
    f)  FORCE_INSTALL=1
        ;;
    esac
done
shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if [ $# -gt 0 ]; then
    echo "[Error] Too may positional arguments."
    echo
    usage
    exit 1
fi

# Check install directory.
if [ -e ${INSTALL_PATH} -a ${FORCE_INSTALL} -eq 0 ]; then
    echo "'${INSTALL_PATH}' already exists, use option -f to force install."
    exit 1
fi

# First install dependencies needed for compilation.
# This may be incomplete as I created this script on a station which had
# already a lot of stuff installed. In such a case, compilation would fail with
# a message indicating the missing library (hopefully). This should be added to
# the list below.
echo_y "Installing dependencies."
# TODO uncomment
# sudo apt-get install -y \
    # git\
    # build-essential\
    # cmake\
    # python-dev\
    # python3-dev\
    # libncurses5-dev\
    # exuberant-ctags



echo_y "Cloning Vim from Github to '${DL_DIRPATH}'."
# TODO uncomment
# rm -rf ${DL_DIRPATH}
# git clone https://github.com/vim/vim.git ${DL_DIRPATH}

echo_y "Configuring Vim."
# TODO uncomment
# cd ${DL_DIRPATH}
# ./configure \
    # --prefix=${INSTALL_PATH} \
    # --enable-fail-if-missing \
    # --with-features=huge \
    # --disable-gui \
    # --with-x \
    # --enable-multibyte \
    # --enable-xim \
    # --enable-xsmp \
    # --disable-xsmp-interact \
    # --with-tlib=ncurses \
    # --enable-pythoninterp \
    # --enable-python3interp
echo_y "Making Vim."
# make clean
# make
echo_y "Installing Vim."
# sudo rm -rf ${INSTALL_PATH}
# sudo make install
echo_y "Deleting '${DL_DIRPATH}'."
# TODO uncomment
# rm -rf ${DL_DIRPATH}
#git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo_g "Vim successfully installed to '${INSTALL_PATH}'."
